version: 1
jobs:
  build:
    docker:
        - image: circleci/golang:1.10-stretch
    working_directory: /go/src/github.com/carloruiz/disco-site.git
    steps:
        - checkout
        - run: go get
        - run: go test -v            
        
